config/routes.rb
require File.join(Rails.root, 'app/models/openid_providers/google_openid')
require File.join(Rails.root, 'app/models/openid_providers/github_oauth')

ScalarmExperimentManager::Application.routes.draw do

  resources :simulation_managers do
    member do
      get :code
    end
  end

  root 'user_controller#index'

  get 'login' => 'user_controller#login'
  post 'login' => 'user_controller#login'
  post 'logout' => 'user_controller#logout'
  get 'user_controller/account'
  post 'user_controller/change_password'
  get 'status' => 'user_controller#status'

  if GoogleOpenID.google_configured?
    get 'login/login_oauth_google' => 'user_controller#login_oauth_google'
    get 'login/oauth2_google_callback' => 'user_controller#oauth2_google_callback'
  end

  if GithubOauth.github_configured?
    get 'login/login_oauth_github' => 'user_controller#login_oauth_github'
    get 'login/oauth2_github_callback' => 'user_controller#oauth2_github_callback'
  end

  get 'login/login_openid_plgrid' => 'user_controller#login_openid_plgrid'
  post 'login/openid_callback_plgrid' => 'user_controller#openid_callback_plgrid'

  get 'simulation_scenarios' => 'simulations#index'
  get 'simulations' => 'simulations#index'
  get 'simulations/index'
  get 'simulations/registration'
  post 'simulations/upload_component'
  post 'simulations/destroy_component'
  post 'simulations' => 'simulations#create'

  get 'infrastructures' => 'infrastructures#index'

  resources :experiments do
    collection do
      post :start_import_based_experiment, to: 'experiments#create'
      post :calculate_experiment_size
      post :calculate_imported_experiment_size
      get :running_experiments
      get :completed_experiments
      get :historical_experiments
      get :random_experiment
    end

    member do
      get   :code_base
      get   :next_simulation
      get   :parameter_values
      get   :file_with_configurations
      get   :configurations
      get   :results_binaries

      post  :stop
      post  :extend_input_values
      get   :intermediate_results
      get   :extension_dialog
      post  :change_scheduling_policy
      post  :schedule_point
      post  :schedule_multiple_points
      get   :get_result

      post :histogram
      post :scatter_plot
      post :regression_tree
      get :scatter_plot_series

      get :running_simulations_table
      get :completed_simulations_table

      get :completed_simulations_count
      get :experiment_stats, to: 'experiments#stats'
      get :stats
      get :experiment_moes, to: 'experiments#moes'
      get :moes
      get :moes_json
      get :results_info

      get :simulation_manager

      post :share

      post :mark_as_complete

      post 'supervisor_run/state_history', action: :post_supervisor_state_history
      get 'supervisor_run/state_history', action: :get_supervisor_state_history

      get :analysis_panel
    end

    resources :simulations do
      member do
        post :mark_as_complete
        post :progress_info
        get  :progress_info_history
        get  :get_simulation_data
        get  :results_binaries
        get  :results_stdout
        post :host_info
        post :performance_stats
      end
    end
  end

  get 'simulations/simulation_scenarios' => 'simulations#simulation_scenarios'
  post 'simulations/upload_parameter_space'

  resource :infrastructure do
    member do
      post :schedule_simulation_managers
      get :infrastructure_info
      post :add_infrastructure_credentials
      get :get_infrastructure_credentials
      post :remove_credentials
    end

    collection do
      get :list
      get :simulation_managers_info
      get :simulation_managers_summary
      get :get_sm_dialog
      get :get_booster_dialog
      get :get_booster_partial
      get :get_credentials_partial
      get :get_credentials_table_partial
      get :get_resource_status
      get :simulation_manager_records
      post :simulation_manager_command
    end
  end

  resources 'simulation_scenarios' do
    member do
      get :code_base
      post :share
      get :experiments
    end
  end

  resources :clusters do
    collection do
      get :credentials
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
  Sidekiq::Web.set :sessions, Rails.application.config.session_options

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets.sidekiq_username && password == Rails.application.secrets.sidekiq_password
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :information do
    get     'status' => 'status#status'
    get     'scalarm_status' => 'status#scalarm_status'

    get     'db_instances/list'
    post    'db_instances/register'
    post    'db_instances/deregister'

    post    'db_instances' => 'db_instances#register'
    get     'db_instances' => 'db_instances#list'
    delete  'db_instances' => 'db_instances#deregister'

    get     'db_config_services/list'
    post    'db_config_services/register'
    post    'db_config_services/deregister'

    post    'db_config_services' => 'db_config_services#register'
    get     'db_config_services' => 'db_config_services#list'
    delete  'db_config_services' => 'db_config_services#deregister'

    get     'db_routers/list'
    post    'db_routers/register'
    post    'db_routers/deregister'

    post    'db_routers' => 'db_routers#register'
    get     'db_routers' => 'db_routers#list'
    delete  'db_routers' => 'db_routers#deregister'

    get 'storage/list'
    post 'storage/register'
    post 'storage/deregister'

    post 'experiments/register'
    get 'experiments/list'
    post 'experiments/deregister'

    post 'experiment_managers' => 'experiments#register'
    get 'experiment_managers' => 'experiments#list'
    delete 'experiment_managers' => 'experiments#deregister'

    post 'storage_managers' => 'storage#register'
    get 'storage_managers' => 'storage#list'
    delete 'storage_managers' => 'storage#deregister'

    post 'chart_services' => 'chart#register'
    get 'chart_services' => 'chart#list'
    delete 'chart_services' => 'chart#deregister'

    post 'data_explorers' => 'chart#register'
    get 'data_explorers' => 'chart#list'
    delete 'data_explorers' => 'chart#deregister'

    post 'experiment_supervisors' => 'supervisor#register'
    get 'experiment_supervisors' => 'supervisor#list'
    delete 'experiment_supervisors' => 'supervisor#deregister'
  end

  namespace :storage do
    get '/status' => 'log_bank#status'
    put 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#put_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#get_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id/size' => 'log_bank#get_simulation_output_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#delete_simulation_output'

    get 'experiments/:experiment_id' => 'log_bank#get_experiment_output'
    get 'experiments/:experiment_id/size' => 'log_bank#get_experiment_output_size'
    delete 'experiments/:experiment_id' => 'log_bank#delete_experiment_output'

    put 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#put_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#get_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout_size' => 'log_bank#get_simulation_stdout_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#delete_simulation_stdout'
  end

end

app/helpers/infrastructures_helper.rb
require 'infrastructure_facades/infrastructure_facade_factory'
require 'json'

module InfrastructuresHelper

  # Changes hash-data from InfrastrctureController.list to data for selector with groups
  def infrastructures_list_to_select_data(infrastructures_hash)
    disabled_keys = []
    data = infrastructures_hash.map do |first|
      first[:children] = [first.clone] unless first.has_key? :children
      [
          first[:name], first[:children].map do |second|
            key = second[:infrastructure_name]
            if second[:enabled] == false
              disabled_keys << key
            end
            [second[:name], key]
          end
      ]
    end

    {data: data, disabled: disabled_keys}
  end

  def image_secrets_select_data(user_id, cloud_name)
    CloudImageSecrets.find_all_by_query(user_id: user_id, cloud_name: cloud_name.to_s).map do |i|
      ["#{i.image_identifier} #{i.label ? i.label : ''} (#{i.image_login})", i.id]
    end
  end

  def instance_types_select_data(cloud_client)
    cloud_client.instance_types.map{|k, desc| [desc, k]}
  end

  def private_machine_credentials_select_data(user_id)
    PrivateMachineCredentials.where(user_id: user_id).map{|mach| [mach.machine_desc, mach.id]}
  end

  def infrastructure_long_name(infrastructure_name)
    InfrastructureFacadeFactory.get_facade_for(infrastructure_name).long_name
  end

  def count_simulation_managers(infrastructure_name, user_id)
    InfrastructureFacadeFactory.get_facade_for(infrastructure_name).count_sm_records(user_id)
  end

  def experiments_select_data(user)
    shared_prefix = "[#{I18n.t('infrastructure.information.shared_experiment')}] "
    user.get_running_experiments.map do |exp|
      ["#{user.owns?(exp) ? '' : shared_prefix}#{exp.name} (#{exp.id})", exp.id]
    end
  end

end

app/views/infrastructures/_booster_dialog.html.haml
- infrastructure_name = InfrastructureFacadeFactory.get_registered_infrastructure_names.first if infrastructure_name.blank?
- infrastructures_list = infrastructures_list_to_select_data(InfrastructureFacadeFactory.list_infrastructures(current_user.id))
- infrastructures_select_data = infrastructures_list[:data]
- disabled_infrastructures = infrastructures_list[:disabled]
-if disabled_infrastructures.include? infrastructure_name
  - InfrastructureFacadeFactory.get_registered_infrastructure_names.each do |i|
    - infrastructure_name = i unless disabled_infrastructures.include? i
    - break unless disabled_infrastructures.include? i
%h2= t('experiments.monitoring_actions.booster.header')

%a.close-reveal-modal &#215;

%dl.accordion(data-accordion)
  %dd
    %a(href="#submission-panel")= t 'infrastructure.information.submission_label'
    .content.active#submission-panel
      #scheduler-form
        = form_tag schedule_simulation_managers_infrastructure_path(format: 'json'), remote: true, class: 'custom', "data-abide" => '', :'data-type' => 'json', multipart: false do
          = tag(:input, type: "hidden", name: request_forgery_protection_token.to_s, value: form_authenticity_token)
          .row
            .large-4.columns
              = label_tag :experiment_id, t('infrastructure.information.experiment') + ':', class: 'inline right'
            .large-4.columns
              = select_tag :experiment_id, options_for_select(experiments_select_data(current_user), experiment_id.to_s)
            .large-1.columns
          .row
            .large-4.columns
              = label_tag :infrastructure_name, t('infrastructure.information.infrastructure') + ':', class: 'inline right'
            .large-4.columns
              = select_tag :infrastructure_name, grouped_options_for_select(infrastructures_select_data,
                infrastructure_name)
            .large-1.columns

          .row
            .large-4.columns
              = label_tag :job_counter,  t('infrastructure.information.instance_counter') + ':', class: 'inline right'
            .large-4.columns
              = number_field_tag :job_counter, 1, in: 1..100, step: 1, required: true, pattern: "^\\d+$", class: 'text-right'
              %small(class="error") Invalid job counter value
            .large-1.columns

          #infrastructure_fields

          .row
            .large-4.columns
              = label_tag :time_limit, t('infrastructure.information.time_constraint') + ':', class: 'inline right'
            .large-4.columns
              = number_field_tag :time_limit, 60, min: 1, step: 1, required: true, pattern: "^\\d+$", class: 'text-right'
              %small(class="error") Invalid time limit value
            .large-1.columns

          .row
            .large-4.columns
              = label_tag :start_at, t('infrastructure.information.start_at') + ':', class: 'inline right'
            .large-4.columns
              = text_field_tag :start_at, ''
            .large-1.columns

          .row#submit-button
            .large-12.columns.text-center
              = submit_tag t('infrastructure.information.submit'), class: 'button radius' , id: "submit-button"

          #invalid-form.reveal-modal(data-reveal="true")
            %h2.subheader.text-center Form has some invalid fields
            .small-12.columns.text-center
              %a#invalid-ok.button.radius.medium= 'OK'

  %dd
    %a(href="#simulation-managers-panel")= t('infrastructure.information.scheduled_label')
    .content#simulation-managers-panel
      .row
        #simulation-managers.large-12.columns




:javascript
  $(function() {
   $("#submission-panel")
        .on('valid.fndtn.abide', function(){

          $('submit-button').click();
        })
        .on('invalid.fndtn.abide', function(){
          $(this).find('[data-invalid]').blur();
          $('#invalid-form').foundation('reveal', 'open');
        });
      $("#invalid-ok").bind("click", function() {
        $('#invalid-form').foundation('reveal', 'close');
        $('#dialog.reveal-modal').foundation('reveal', 'open');
        $('html, body').animate({
          scrollTop: $("#submission-panel").offset().top
        }, 1500);});
    $(document).foundation();
    new window.InfrastructuresBooster("#{infrastructure_name}", #{disabled_infrastructures}, "dialog");
  });

app/views/infrastructures/_error_dialog.html.haml
%h2= t('infrastructure.tree.error_dialog.header')

%a.close-reveal-modal &#215;

= message

app/views/infrastructures/_simulation_managers_summary.html.haml
- states_desc = %w(created initializing running terminating error unknown).map do |state|
  - "<li><div class='tooltip-status-square sm-#{state}'/>&nbsp;&nbsp;#{t("infrastructures.sm_dialog.state.#{state}")}</li>"

- state_tooltip = "#{t('infrastructures.state_tooltip')}" + |
  "<ul class='status-tooltip'> #{states_desc.join("\n")} </ul>" |

.row
  %p.small-12.columns
    = "Total count of simulation managers registered for #{long_name}: #{simulation_managers.count}"

.row
  .small-12.columns
    - begin
      %table(style="width: 100%;" )
        %thead
          %tr
            %th= t('infrastructures.resource_id')
            %th{style: 'text-align: center;'}
              %span.has-tip{'data-tooltip' => '', title: state_tooltip}
                %i.fi-info{style: 'color: black;'}
            %th= t('infrastructures.sm_dialog.sm_initialized_at')
            %th= t('infrastructures.sm_dialog.created_at')
            %th= t('infrastructures.sm_dialog.time_limit')
            %th= t('infrastructures.sm_dialog.experiment')
            %th= t('infrastructures.sm_dialog.specific')
        %tbody
          - simulation_managers.each do |record|
            %tr
              - begin
                = render partial: "infrastructures/scheduler/simulation_manager_info",
                    locals: {partial_name: partial_name, record: record}
              - rescue => e
                %td(colspan="7" )
                  - raise e if e.kind_of? ActionView::MissingTemplate
                  =t('infrastructure.information.sm_record_error', error: e.to_s)
    - rescue ActionView::MissingTemplate
      = t('infrastructure.information.sm_record_no_view')

:javascript
  $(function() {
    $(this).foundation('tooltip');
  });

app/views/infrastructures/_sm_dialog.html.haml
%h2= t('infrastructure.tree.sm_dialog.header')

%a.close-reveal-modal &#215;

- begin
  %h3= t('.resource_header', resource_id: record.resource_id, facade_name: facade.long_name)

  .row.small-12.columns
    .small-2.columns.action-button
      %span#restart_simulation_manager_button{class: button_classes}
        %i.fi-refresh
        = raw '&nbsp;&nbsp;'
        = t('.restart')

    .small-2.columns.action-button
      - if [:error, :terminating].include? record.state
        %span#destroy_record_simulation_manager_button{class: "#{button_classes} alert"}
          %i.fi-x
          = raw '&nbsp;&nbsp;'
          = t('.remove')
      - else
        %span#stop_simulation_manager_button{class: "#{button_classes} alert"}
          %i.fi-stop
          = raw '&nbsp;&nbsp;'
          = t('.stop')
    .small-8.columns

  .row.small-12.columns
    %ul
      - unless record.onsite_monitoring
        %li
          %strong= t('.resource_state') + ': '
          #resource-state{style: 'display: inline;'}
            = image_tag 'loading.gif', size: '16x16'

      -# infrastructure-specific info
      -begin
        = render partial: "infrastructures/scheduler/simulation_managers_info/#{partial_name}", locals: {record: record}
      -rescue ActionView::MissingTemplate => exc
        = exc.to_s
        -# ignore if not found

      -# general record info
      - record_state = t("infrastructures.sm_dialog.state.#{record.state}",
          default: t('infrastructures.sm_dialog.state.unknown'))
      %li
        %strong= t('infrastructures.sm_dialog.simulation_manager_state') + ': '
        =record_state
      - if record.state == :error
        %ul
          %li
            %strong= t('infrastructures.sm_dialog.error_message') + ': '
            = t('infrastructure.information.sm_info.errors.'+record.error, default: record.error)
            - unless record.error_log.nil?
              %li
                %strong= t('infrastructure.information.sm_info.error_log') + ': '
                .panel.log-box
                  - record.error_log.split("\n").each do |line|
                    = line
                    %br
      - elsif record.state == :initialized
        %li
          %strong= t('infrastructures.sm_dialog.sm_initialized_at') + ':'
          #sm-installed-at-date
      %li
        %strong= t('infrastructures.sm_dialog.created_at') + ': '
        #sm-created-at-date{style: 'display: inline;'}
      %li
        %strong= t('infrastructures.sm_dialog.time_limit') + ': '
        ="#{record.time_limit.to_s} minutes (will work until: "
        - time_limit_until = record.created_at.since(record.time_limit.to_i.minutes).to_i
        #sm-time-limit-until{style: 'display: inline'}
        =')'
      %li
        %strong= t('infrastructures.sm_dialog.experiment') + ': '
        - if record.experiment
          = link_to "#{record.experiment.name}", experiment_path(record.experiment_id)
        - else
          = t('infrastructure.information.sm_record_error', error: t('infrastructure.information.experiment_not_found'))


- rescue => e
  =t('infrastructure.information.sm_record_error', error: e.to_s)

:javascript
  $(function() {
    $(document).foundation();

    new window.SmDialog("#dialog", "#{facade.short_name}", "#{record.id}");

    display_date("#sm-initialized-at-date", #{record.initialized_at.to_i});
    display_date("#sm-created-at-date", #{record.created_at.to_i});
    display_date("#sm-time-limit-until", #{time_limit_until});
  });