config/routes.rb
require File.join(Rails.root, 'app/models/openid_providers/google_openid')
require File.join(Rails.root, 'app/models/openid_providers/github_oauth')

ScalarmExperimentManager::Application.routes.draw do

  resources :simulation_managers do
    member do
      get :code
    end
  end

  root 'user_controller#index'

  get 'login' => 'user_controller#login'
  post 'login' => 'user_controller#login'
  post 'logout' => 'user_controller#logout'
  get 'user_controller/account'
  post 'user_controller/change_password'
  get 'status' => 'user_controller#status'

  if GoogleOpenID.google_configured?
    get 'login/login_oauth_google' => 'user_controller#login_oauth_google'
    get 'login/oauth2_google_callback' => 'user_controller#oauth2_google_callback'
  end

  if GithubOauth.github_configured?
    get 'login/login_oauth_github' => 'user_controller#login_oauth_github'
    get 'login/oauth2_github_callback' => 'user_controller#oauth2_github_callback'
  end

  get 'login/login_openid_plgrid' => 'user_controller#login_openid_plgrid'
  post 'login/openid_callback_plgrid' => 'user_controller#openid_callback_plgrid'

  get 'simulation_scenarios' => 'simulations#index'
  get 'simulations' => 'simulations#index'
  get 'simulations/index'
  get 'simulations/registration'
  post 'simulations/upload_component'
  post 'simulations/destroy_component'
  post 'simulations' => 'simulations#create'

  get 'infrastructures' => 'infrastructures#index'

  resources :experiments do
    collection do
      post :start_import_based_experiment, to: 'experiments#create'
      post :calculate_experiment_size
      post :calculate_imported_experiment_size
      get :running_experiments
      get :completed_experiments
      get :historical_experiments
      get :random_experiment
    end

    member do
      get   :code_base
      get   :next_simulation
      get   :parameter_values
      get   :file_with_configurations
      get   :configurations
      get   :results_binaries

      post  :stop
      post  :extend_input_values
      get   :intermediate_results
      get   :extension_dialog
      post  :change_scheduling_policy
      post  :schedule_point
      post  :schedule_multiple_points
      get   :get_result

      post :histogram
      post :scatter_plot
      post :regression_tree
      get :scatter_plot_series

      get :running_simulations_table
      get :completed_simulations_table

      get :completed_simulations_count
      get :experiment_stats, to: 'experiments#stats'
      get :stats
      get :experiment_moes, to: 'experiments#moes'
      get :moes
      get :moes_json
      get :results_info

      get :simulation_manager

      post :share

      post :mark_as_complete

      post 'supervisor_run/state_history', action: :post_supervisor_state_history
      get 'supervisor_run/state_history', action: :get_supervisor_state_history

      get :analysis_panel
    end

    resources :simulations do
      member do
        post :mark_as_complete
        post :progress_info
        get  :progress_info_history
        get  :get_simulation_data
        get  :results_binaries
        get  :results_stdout
        post :host_info
        post :performance_stats
      end
    end
  end

  get 'simulations/simulation_scenarios' => 'simulations#simulation_scenarios'
  post 'simulations/upload_parameter_space'

  resource :infrastructure do
    member do
      post :schedule_simulation_managers
      get :infrastructure_info
      post :add_infrastructure_credentials
      get :get_infrastructure_credentials
      post :remove_credentials
    end

    collection do
      get :list
      get :simulation_managers_info
      get :simulation_managers_summary
      get :get_sm_dialog
      get :get_booster_dialog
      get :get_booster_partial
      get :get_credentials_partial
      get :get_credentials_table_partial
      get :get_resource_status
      get :simulation_manager_records
      post :simulation_manager_command
    end
  end

  resources 'simulation_scenarios' do
    member do
      get :code_base
      post :share
      get :experiments
    end
  end

  resources :clusters do
    collection do
      get :credentials
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
  Sidekiq::Web.set :sessions, Rails.application.config.session_options

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets.sidekiq_username && password == Rails.application.secrets.sidekiq_password
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :information do
    get     'status' => 'status#status'
    get     'scalarm_status' => 'status#scalarm_status'

    get     'db_instances/list'
    post    'db_instances/register'
    post    'db_instances/deregister'

    post    'db_instances' => 'db_instances#register'
    get     'db_instances' => 'db_instances#list'
    delete  'db_instances' => 'db_instances#deregister'

    get     'db_config_services/list'
    post    'db_config_services/register'
    post    'db_config_services/deregister'

    post    'db_config_services' => 'db_config_services#register'
    get     'db_config_services' => 'db_config_services#list'
    delete  'db_config_services' => 'db_config_services#deregister'

    get     'db_routers/list'
    post    'db_routers/register'
    post    'db_routers/deregister'

    post    'db_routers' => 'db_routers#register'
    get     'db_routers' => 'db_routers#list'
    delete  'db_routers' => 'db_routers#deregister'

    get 'storage/list'
    post 'storage/register'
    post 'storage/deregister'

    post 'experiments/register'
    get 'experiments/list'
    post 'experiments/deregister'

    post 'experiment_managers' => 'experiments#register'
    get 'experiment_managers' => 'experiments#list'
    delete 'experiment_managers' => 'experiments#deregister'

    post 'storage_managers' => 'storage#register'
    get 'storage_managers' => 'storage#list'
    delete 'storage_managers' => 'storage#deregister'

    post 'chart_services' => 'chart#register'
    get 'chart_services' => 'chart#list'
    delete 'chart_services' => 'chart#deregister'

    post 'data_explorers' => 'chart#register'
    get 'data_explorers' => 'chart#list'
    delete 'data_explorers' => 'chart#deregister'

    post 'experiment_supervisors' => 'supervisor#register'
    get 'experiment_supervisors' => 'supervisor#list'
    delete 'experiment_supervisors' => 'supervisor#deregister'
  end

  namespace :storage do
    get '/status' => 'log_bank#status'
    put 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#put_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#get_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id/size' => 'log_bank#get_simulation_output_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#delete_simulation_output'

    get 'experiments/:experiment_id' => 'log_bank#get_experiment_output'
    get 'experiments/:experiment_id/size' => 'log_bank#get_experiment_output_size'
    delete 'experiments/:experiment_id' => 'log_bank#delete_experiment_output'

    put 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#put_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#get_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout_size' => 'log_bank#get_simulation_stdout_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#delete_simulation_stdout'
  end

end

app/controllers/api/simulation_scenarios_controller.rb
class Api::SimulationScenariosController < Api::ApplicationController

  def index
    render json: []
  end

  def show
    render json: {}
  end

end

app/controllers/simulation_scenarios_controller.rb
require 'zip'

class SimulationScenariosController < ApplicationController
  include AdaptersSetup
  before_filter :load_simulation_scenario, except: [ :index, :create ]

  def index

  end

  def edit
    if @simulation_scenario.blank? or @simulation_scenario.user_id != current_user.id
      flash[:error] = t('simulation_scenarios.not_owned_by', id: params[:id], user: current_user.login)
      redirect_to simulations_path
    else
      @input_writers = SimulationInputWriter.find_all_by_user_id(current_user.id).map{|ex| [ex.name, ex._id]}.unshift(["None", nil])
      @executors = SimulationExecutor.find_all_by_user_id(current_user.id).map{|ex| [ex.name, ex._id]}.unshift(["None", nil])
      @output_readers = SimulationOutputReader.find_all_by_user_id(current_user.id).map{|ex| [ex.name, ex._id]}.unshift(["None", nil])
      @progress_monitors = SimulationProgressMonitor.find_all_by_user_id(current_user.id).map{|ex| [ex.name, ex._id]}.unshift(["None", nil])
    end
  end

  def update
    # TODO if necessary - validate simulation_input and simulation_binaries somehow

    if @simulation_scenario.blank? or @simulation_scenario.user_id != current_user.id
      flash[:error] = t('simulation_scenarios.not_owned_by', id: params[:id], user: current_user.login)
    else
      simulation_input =  params.include?(:simulation_input) ? Utils.parse_json_if_string(Utils.read_if_file(params[:simulation_input])) : nil
      simulation_scenario_params_validation(simulation_input)

      # simulation update
      if flash[:error].nil?
        @simulation_scenario.name = params[:simulation_name]
        @simulation_scenario.description = params[:simulation_description]
        @simulation_scenario.input_specification = simulation_input unless simulation_input.blank?
        @simulation_scenario.created_at = Time.now

        begin
          set_up_adapter_checked(@simulation_scenario, 'input_writer', current_user, params, false)
          set_up_adapter_checked(@simulation_scenario, 'executor', current_user, params)
          set_up_adapter_checked(@simulation_scenario, 'output_reader', current_user, params, false)
          set_up_adapter_checked(@simulation_scenario, 'progress_monitor', current_user, params, false)

          unless (binaries = params[:simulation_binaries]).blank?
            @simulation_scenario.set_simulation_binaries(binaries.original_filename, binaries.read)
          end

          @simulation_scenario.save

          flash[:notice] = t('simulation_scenarios.update.success', name: @simulation_scenario.name) if flash[:error].nil?
        rescue SecurityError => e
          raise e
        rescue => e
          flash[:error] = t('simulations.create.internal_error') unless flash[:error]
          Rails.logger.error("Exception occurred when setting up adapters or binaries: #{e}\n#{e.backtrace.join("\n")}")
        end
      end
    end

    respond_to do |format|
      format.json { render json: { status: (flash[:error].nil? ? 'ok' : 'error'), simulation_id: simulation.id.to_s } }
      format.html { redirect_to simulations_path }
    end
  end

  def create
  end

  def show
    render json: (
        if @simulation_scenario
          {status: 'ok', data: @simulation_scenario.to_h }
        else
          {status: 'error', error_code: 'not_found'}
        end
    )
  end

  def experiments
    experiment_ids = current_user.experiments.where({simulation_id: @simulation_scenario.id}, {fields: ["_id"]}).map{|obj| obj.id.to_s}

    render json: (
           if experiment_ids
             {status: 'ok', experiments: experiment_ids}
           else
             {status: 'error', data: 'not_found'}
           end
           )
  end

  def code_base
    if @simulation_scenario.blank?
      render inline: t('simulation_scenarios.not_found', id: params[:id]), status: 404
    else
      code_base_dir = Dir.mktmpdir('code_base')

      file_list = %w(input_writer executor output_reader progress_monitor)
      file_list.each do |filename|
        unless @simulation_scenario.send(filename).nil?
          IO.write("#{code_base_dir}/#{filename}", @simulation_scenario.send(filename).code)
        end
      end
      IO.binwrite("#{code_base_dir}/simulation_binaries.zip", @simulation_scenario.simulation_binaries)
      file_list << 'simulation_binaries.zip'

      IO.binwrite("#{code_base_dir}/input.json", @simulation_scenario.input_specification.to_json)
      file_list << 'input.json'

      zipfile_name = File.join('/tmp', "simulation_scenario_#{@simulation_scenario.id}_code_base.zip")

      File.delete(zipfile_name) if File.exist?(zipfile_name)

      Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
        file_list.each do |filename|
          if File.exist?(File.join(code_base_dir, filename))
            zipfile.add(filename, File.join(code_base_dir, filename))
          end
        end
      end

      FileUtils.rm_rf(code_base_dir)

      send_file zipfile_name, type: 'application/zip'
    end
  end

  def destroy
    if @simulation_scenario.blank?
      render inline: t('simulation_scenarios.not_found', id: params[:id]), status: 404
    elsif @simulation_scenario.user_id != @current_user.id
      flash[:error] = t('simulation_scenarios.not_owned_by', id: params[:id], user: @current_user.login)
    else
      flash[:notice] = t('simulations.destroy', name: @simulation_scenario.name)
      @simulation_scenario.destroy
    end

    redirect_to simulations_path
  end

  def share
    validate(
        mode: :security_default
    )
    # TODO validate sharing with login params - it should denote scalarm user login

    @user = nil

    if (not params.include?('sharing_with_login')) or (@user = ScalarmUser.find_by_login(params[:sharing_with_login].to_s)).blank?
      flash[:error] = t('experiments.user_not_found', { user: params[:sharing_with_login] })
    end

    if @simulation_scenario.blank? or @simulation_scenario.user_id != current_user.id
      flash[:error] = t('simulation_scenarios.not_owned_by', { id: params[:id], user: params[:sharing_with_login] })
    end

    if flash[:error].blank?
      if ['share', 'unshare'].include?(params[:mode])
        sharing_list = @simulation_scenario.shared_with
        sharing_list = [ ] if sharing_list.nil?
        if params[:mode] == 'unshare'
          sharing_list.delete_if{|x| x == @user.id}
        else
          sharing_list << @user.id
        end

        @simulation_scenario.shared_with = sharing_list

      elsif ['share_with_all', 'unshare_with_all'].include?(params[:mode])
        @simulation_scenario.is_public = (params[:mode] == 'share_with_all')
      end

      @simulation_scenario.save

      flash[:notice] = t("simulation_scenarios.edit.share.#{params[:mode]}", { name: @simulation_scenario.name, user: @user.login })
    end

    if @simulation_scenario.blank?
      redirect_to simulations_path
    else
      redirect_to edit_simulation_scenario_path(@simulation_scenario.id)
    end
  end

  private

  def simulation_scenario_params_validation(simulation_input)
    case true
      when (not simulation_input.blank?)
        begin
          Utils.parse_json_if_string(simulation_input)
        rescue
          flash[:error] = t('simulations.create.bad_simulation_input')
        end

      when (not (scenarios = Simulation.where({user_id: current_user.id, name: params[:simulation_name].to_s})).blank?)
        unless scenarios.size == 1 and scenarios.first.id == @simulation_scenario.id
          flash[:error] = t('simulations.create.simulation_invalid_name')
        end
    end
  end

  private

  def load_simulation_scenario
    validate(
        id: [:optional, :security_default],
        name: [:optional, :security_default]
    )

    users_scenarios = current_user.get_simulation_scenarios

    @simulation_scenario = if params[:id]
                             users_scenarios.find{|scenario| scenario.id.to_s == params[:id]}
                           elsif
                             users_scenarios.find{|scenario| scenario.id.to_s == params[:name]}
                           else
                             nil
                           end
  end
end

app/helpers/simulation_scenarios_helper.rb
module SimulationScenariosHelper

  def share_scenario_with_users
    ScalarmUser.all.select{|u|
      u.id != current_user.id and (@simulation_scenario.shared_with.blank? or (not @simulation_scenario.shared_with.include?(u.id)))
    }.map{ |u|
      u.login.nil? ? u.email : u.login
    }
  end

end

app/views/simulation_scenarios/create.html.erb
<h1>SimulationScenarios#create</h1>
<p>Find me in app/views/simulation_scenarios/create.html.erb</p>

app/views/simulation_scenarios/edit.html.haml
%section.panel.radius
  = link_to '#', title: t(".share.tooltip"), 'data-reveal-id' => 'share-dialog', disabled: false, class: 'button tiny radius right' do
    = content_tag(:i, '', class: 'fi-share')
    = t(".share.link")

  %h3.subheader= t('.header', name: @simulation_scenario.name)

  .content
    = form_tag(simulation_scenario_path(@simulation_scenario.id), id: 'scenario_form',
      multipart: true, class: 'custom', method: :put, "data-abide" => '') do

      .row
        %fieldset
          %legend= t("simulations.registration.basic_information")
          .row
            .small-3.columns
              %label.right.inline{for: 'simulation_name'}= t("simulations.registration.simulation_name")
            .small-9.columns
              = text_field_tag 'simulation_name', @simulation_scenario.name, style: 'max-width: 100%;', required: true
              %small(class="error") Invalid simulation name - only letters, digits, '-' and '_'
          .row
            .small-3.columns
              %label.right.inline{for: 'simulation_description'}= t("simulations.registration.simulation_description")
            .small-9.columns
              = text_area_tag 'simulation_description', @simulation_scenario.description, rows: 2, style: 'max-width: 100%;'

        = render partial: 'simulations/input_definition_editor'

        .row
          %fieldset#simulation-files
            %legend= t('simulations.registration.files')
            .row
              .row
                .small-10.columns.small-centered
                  %fieldset
                    %legend= t("simulations.registration.simulation_binaries")
                    .row
                      .small-5.small-centered.columns
                        #current_bin{style: "text-align: center;"}= t("simulations.edit.current_bin") + ': ' + @simulation_scenario.simulation_binaries_name.to_s
                    .row{style: 'margin-top: 15px;'}
                      .small-5.columns
                        %label.right.inline{for: 'binaries_box'}
                          %input(type="checkbox" id="binaries_box" style="display: inline;")
                            = t("simulations.edit.change_bin") + ':'
                      .small-7.columns
                        = file_field_tag 'simulation_binaries', required: 'true'
                        %small(class="error") Simulation binaries file is required

                = content_for :javascript do
                  :javascript
                    $(function() {
                      update_bin_row = function() {
                        if($(this).is(':checked')) {
                          $("#simulation_binaries").enable();
                        } else {
                          $("#simulation_binaries").disable();
                        }
                      }

                      $("#binaries_box").on('change', update_bin_row);
                      $("#binaries_box").change()
                    });


              .row
                = render partial: 'simulations/form_row', object: 'input_writer',
                  locals: { input_element: select_tag('input_writer_id', options_for_select(@input_writers, @simulation_scenario.input_writer_id), class: 'medium') }
                = render partial: 'simulations/form_row', object: 'executor',
                  locals: { input_element: select_tag('executor_id', options_for_select(@executors, @simulation_scenario.executor_id), class: 'medium') }
              .row
                = render partial: 'simulations/form_row', object: 'output_reader',
                  locals: { input_element: select_tag('output_reader_id', options_for_select(@output_readers, @simulation_scenario.output_reader_id), class: 'medium') }
                = render partial: 'simulations/form_row', object: 'progress_monitor',
                  locals: { input_element: select_tag('progress_monitor_id', options_for_select(@progress_monitors, @simulation_scenario.progress_monitor_id), class: 'medium') }

      .row
        .small-2.small-centered.columns
          = submit_tag t('.update_btn'), class: 'button expand radius last-element'

      #invalid-form.reveal-modal(data-reveal="true")
        %h2.subheader.text-center Form has some invalid fields
        .small-12.columns.text-center
          %a#invalid-ok.button.radius.medium= 'OK'

- if @simulation_scenario.user_id == current_user.id
  #share-dialog.reveal-modal(data-reveal)
    %a.close-reveal-modal &#215;
    %h2= t ".share.tooltip"

    = form_tag share_simulation_scenario_path(@simulation_scenario.id), class: 'custom' do
      = hidden_field_tag 'mode', 'share'
      .row
        .small-4.columns
          %label.inline.right(for="sharing_with_login")
            = t('experiments.monitoring_actions.share_with_login') + ':'
        .small-3.columns
          = text_field_tag('sharing_with_login')
        .small-3.columns
          = submit_tag t('experiments.monitoring_actions.share'), class: 'button radius small'
        .small-1.columns

    .row
      - if @simulation_scenario.user_id == current_user.id
        .small-4.columns
          %h5.subheader.right= t('simulations.conduct_experiment.simulation_overview_shared_with') + ':'
        .small-8.columns
          %h5.subheader
            - if @simulation_scenario.shared_with.blank?
              = t('experiments.monitoring_actions.blank_shared_with_list')
            - else
              - @simulation_scenario.shared_with.to_a.map{|id| ScalarmUser.find_by_id(id.to_s) }.each do |u|
                = form_tag share_simulation_scenario_path(@simulation_scenario.id), class: 'custom', style: "display: inline;" do
                  = hidden_field_tag 'mode', 'unshare'
                  = hidden_field_tag 'sharing_with_login', u.login
                  = u.login
                  = submit_tag raw("&#215; #{t('experiments.monitoring_actions.unshare')}"), class: 'button radius tiny'
                &nbsp;

    .row
      .small-3.columns.small-centered
        = form_tag share_simulation_scenario_path(@simulation_scenario.id), class: 'custom' do
          = hidden_field_tag 'sharing_with_login', current_user.login

          - if @simulation_scenario.is_public
            = hidden_field_tag 'mode', 'unshare_with_all'
            = submit_tag t('experiments.monitoring_actions.make_private'), class: 'button radius'
          - else
            = hidden_field_tag 'mode', 'share_with_all'
            = submit_tag t('experiments.monitoring_actions.share_with_all'), class: 'button radius'


= content_for :javascript do
  :javascript
    $(function() {
      window.scenario_registration = new window.ScenarioRegistration(#{@simulation_scenario.input_specification.to_json});

      var logins = #{share_scenario_with_users.to_json};

      $("#sharing_with_login").autocomplete({
        source: logins
      });

      $('.ui-autocomplete').addClass('f-dropdown').css("z-index", 1006);
      $("#scenario_form")
        .on('valid.fndtn.abide', function(){

          $('.last-element h3:first').click();
        })
        .on('invalid.fndtn.abide', function(){
          $(this).find('[data-invalid]').blur();
          $('#invalid-form').foundation('reveal', 'open');
        });
      $("#invalid-ok").bind("click", function() {
        $('#invalid-form').foundation('reveal', 'close');
        $('html, body').animate({
          scrollTop: $("#scenario_form").offset().top
        }, 2000);});

    });

app/views/simulation_scenarios/index.html.erb
<h1>SimulationScenarios#index</h1>
<p>Find me in app/views/simulation_scenarios/index.html.erb</p>

app/views/simulation_scenarios/show.html.erb
<h1>SimulationScenarios#show</h1>
<p>Find me in app/views/simulation_scenarios/show.html.erb</p>