config/routes.rb
require File.join(Rails.root, 'app/models/openid_providers/google_openid')
require File.join(Rails.root, 'app/models/openid_providers/github_oauth')

ScalarmExperimentManager::Application.routes.draw do

  resources :simulation_managers do
    member do
      get :code
    end
  end

  root 'user_controller#index'

  get 'login' => 'user_controller#login'
  post 'login' => 'user_controller#login'
  post 'logout' => 'user_controller#logout'
  get 'user_controller/account'
  post 'user_controller/change_password'
  get 'status' => 'user_controller#status'

  if GoogleOpenID.google_configured?
    get 'login/login_oauth_google' => 'user_controller#login_oauth_google'
    get 'login/oauth2_google_callback' => 'user_controller#oauth2_google_callback'
  end

  if GithubOauth.github_configured?
    get 'login/login_oauth_github' => 'user_controller#login_oauth_github'
    get 'login/oauth2_github_callback' => 'user_controller#oauth2_github_callback'
  end

  get 'login/login_openid_plgrid' => 'user_controller#login_openid_plgrid'
  post 'login/openid_callback_plgrid' => 'user_controller#openid_callback_plgrid'

  get 'simulation_scenarios' => 'simulations#index'
  get 'simulations' => 'simulations#index'
  get 'simulations/index'
  get 'simulations/registration'
  post 'simulations/upload_component'
  post 'simulations/destroy_component'
  post 'simulations' => 'simulations#create'

  get 'infrastructures' => 'infrastructures#index'

  resources :experiments do
    collection do
      post :start_import_based_experiment, to: 'experiments#create'
      post :calculate_experiment_size
      post :calculate_imported_experiment_size
      get :running_experiments
      get :completed_experiments
      get :historical_experiments
      get :random_experiment
    end

    member do
      get   :code_base
      get   :next_simulation
      get   :parameter_values
      get   :file_with_configurations
      get   :configurations
      get   :results_binaries

      post  :stop
      post  :extend_input_values
      get   :intermediate_results
      get   :extension_dialog
      post  :change_scheduling_policy
      post  :schedule_point
      post  :schedule_multiple_points
      get   :get_result

      post :histogram
      post :scatter_plot
      post :regression_tree
      get :scatter_plot_series

      get :running_simulations_table
      get :completed_simulations_table

      get :completed_simulations_count
      get :experiment_stats, to: 'experiments#stats'
      get :stats
      get :experiment_moes, to: 'experiments#moes'
      get :moes
      get :moes_json
      get :results_info

      get :simulation_manager

      post :share

      post :mark_as_complete

      post 'supervisor_run/state_history', action: :post_supervisor_state_history
      get 'supervisor_run/state_history', action: :get_supervisor_state_history

      get :analysis_panel
    end

    resources :simulations do
      member do
        post :mark_as_complete
        post :progress_info
        get  :progress_info_history
        get  :get_simulation_data
        get  :results_binaries
        get  :results_stdout
        post :host_info
        post :performance_stats
      end
    end
  end

  get 'simulations/simulation_scenarios' => 'simulations#simulation_scenarios'
  post 'simulations/upload_parameter_space'

  resource :infrastructure do
    member do
      post :schedule_simulation_managers
      get :infrastructure_info
      post :add_infrastructure_credentials
      get :get_infrastructure_credentials
      post :remove_credentials
    end

    collection do
      get :list
      get :simulation_managers_info
      get :simulation_managers_summary
      get :get_sm_dialog
      get :get_booster_dialog
      get :get_booster_partial
      get :get_credentials_partial
      get :get_credentials_table_partial
      get :get_resource_status
      get :simulation_manager_records
      post :simulation_manager_command
    end
  end

  resources 'simulation_scenarios' do
    member do
      get :code_base
      post :share
      get :experiments
    end
  end

  resources :clusters do
    collection do
      get :credentials
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
  Sidekiq::Web.set :sessions, Rails.application.config.session_options

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets.sidekiq_username && password == Rails.application.secrets.sidekiq_password
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :information do
    get     'status' => 'status#status'
    get     'scalarm_status' => 'status#scalarm_status'

    get     'db_instances/list'
    post    'db_instances/register'
    post    'db_instances/deregister'

    post    'db_instances' => 'db_instances#register'
    get     'db_instances' => 'db_instances#list'
    delete  'db_instances' => 'db_instances#deregister'

    get     'db_config_services/list'
    post    'db_config_services/register'
    post    'db_config_services/deregister'

    post    'db_config_services' => 'db_config_services#register'
    get     'db_config_services' => 'db_config_services#list'
    delete  'db_config_services' => 'db_config_services#deregister'

    get     'db_routers/list'
    post    'db_routers/register'
    post    'db_routers/deregister'

    post    'db_routers' => 'db_routers#register'
    get     'db_routers' => 'db_routers#list'
    delete  'db_routers' => 'db_routers#deregister'

    get 'storage/list'
    post 'storage/register'
    post 'storage/deregister'

    post 'experiments/register'
    get 'experiments/list'
    post 'experiments/deregister'

    post 'experiment_managers' => 'experiments#register'
    get 'experiment_managers' => 'experiments#list'
    delete 'experiment_managers' => 'experiments#deregister'

    post 'storage_managers' => 'storage#register'
    get 'storage_managers' => 'storage#list'
    delete 'storage_managers' => 'storage#deregister'

    post 'chart_services' => 'chart#register'
    get 'chart_services' => 'chart#list'
    delete 'chart_services' => 'chart#deregister'

    post 'data_explorers' => 'chart#register'
    get 'data_explorers' => 'chart#list'
    delete 'data_explorers' => 'chart#deregister'

    post 'experiment_supervisors' => 'supervisor#register'
    get 'experiment_supervisors' => 'supervisor#list'
    delete 'experiment_supervisors' => 'supervisor#deregister'
  end

  namespace :storage do
    get '/status' => 'log_bank#status'
    put 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#put_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#get_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id/size' => 'log_bank#get_simulation_output_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#delete_simulation_output'

    get 'experiments/:experiment_id' => 'log_bank#get_experiment_output'
    get 'experiments/:experiment_id/size' => 'log_bank#get_experiment_output_size'
    delete 'experiments/:experiment_id' => 'log_bank#delete_experiment_output'

    put 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#put_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#get_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout_size' => 'log_bank#get_simulation_stdout_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#delete_simulation_stdout'
  end

end

app/models/information/chart_service.rb
class Information::ChartService
  include Mongoid::Document

  field :address, type: String
end

app/controllers/information/abstract_service_controller.rb
# Methods to implement:
# - self.model_class -> return model class
# - self.service_name -> long name for response messages

class Information::AbstractServiceController < ApplicationController
  before_filter :authenticate, :except => [:list]

  def register
    address = params[:address]

    if self.class.model_class.where(address: address).to_a.blank?
      manager = self.class.model_class.new(address: address)
      manager.save

      render json: {status: 'ok', msg: "Success: '#{address}' has been registered as #{self.class.service_name}"}
    else
      render json: {status: 'error', msg: "Failure: '#{address}' is already registered as #{self.class.service_name}"}, status: 500
    end
  end

  def list
    render json: generate_address_list
  end

  def deregister
    address = params[:address]

    self.class.model_class.where(address: address).each(&:destroy)

    render json: {status: 'ok', msg: "Success: '#{address}' has been deregistered as #{self.class.service_name}"}
  end

  def generate_address_list
    self.class.model_class.all.map(&:address)
  end
end

app/controllers/information/chart_controller.rb
class Information::ChartController < Information::AbstractServiceController
  def self.service_name
    'Chart Service'
  end

  def self.model_class
    Information::ChartService
  end
end

app/controllers/information/db_config_services_controller.rb
class Information::DbConfigServicesController < Information::AbstractServiceController
  def self.service_name
    'DbConfigService'
  end

  def self.model_class
    Information::DbConfigService
  end
end

app/controllers/information/db_instances_controller.rb
class Information::DbInstancesController < Information::AbstractServiceController
  def self.service_name
    'DbInstance'
  end

  def self.model_class
    Information::DbInstance
  end
end

app/controllers/information/db_routers_controller.rb
class Information::DbRoutersController < Information::AbstractServiceController
  def self.service_name
    'DbRouter'
  end

  def self.model_class
    Information::DbRouter
  end
end

app/controllers/information/experiments_controller.rb
class Information::ExperimentsController < Information::AbstractServiceController
  def self.service_name
    'Experiment Manager'
  end

  def self.model_class
    Information::ExperimentManager
  end

  # Override parent: add self address if no addresses are registered
  def generate_address_list
    adresses = super
    adresses.blank? ? [ request.host_with_port ] : adresses
  end
end

app/controllers/information/status_controller.rb
require 'xmlsimple'
require 'restclient'

class Information::StatusController < ApplicationController
  rescue_from StandardError, with: :last_rescue

  def last_rescue(exception)
    Rails.logger.error("Fatal error on status check: #{exception.to_s}\n#{exception.backtrace.join("\n")}")
    status = 'failed'
    message = "Fatal error: #{exception.to_s}; see logs for details."
    http_status = :internal_server_error
    data = {
        date: Time.now,
        status: status,
        message: message
    }
    respond_to do |format|
      format.html do
        render text: json_pretty(data),
               status: http_status
      end

      format.json do
        render json: data, status: http_status
      end

      format.xml do
        render xml: convert_status_to_xml(data), status: http_status
      end
    end
  end

  def status
    render nothing: true, status: :ok
  end

  def scalarm_status
    service_controllers_classes = [
      Information::ExperimentsController,
      Information::ChartController,
      Information::SupervisorController,
    ]
    states = Hash[
      service_controllers_classes.collect do |service_class|
        [service_class, collect_service_states(service_class)]
      end
    ]

    status = 'ok'
    message = ''

    if states.values.any?(&:empty?)
      status = 'failed'
      message = 'Every service should have at least one instance.'
    elsif any_service_in_state?('failed', *states.values)
      status = 'failed'
      message = 'One or more service failed. Please check service details.'
    elsif any_service_in_state?('warning', *states.values)
      status = 'warning'
      message = 'One or more service has warnings. Please check service details.'
    end

    # response status for nagios probe: ok, failed, warning
    data = {
        date: Time.now,
        status: status, message: message
    }

    states.each do |service_class, this_service_states|
      add_service_states(
        data,
        this_service_states,
        service_class.service_name.parameterize
      )
    end

    respond_to do |format|
      format.html do
        render text: json_pretty(data),
               status: :ok
      end
      format.json do
        render json: data, status: :ok
      end
      format.xml do
        render xml: convert_status_to_xml(data), status: :ok
      end
    end
  end

  def convert_status_to_xml(data)
    XmlSimple.xml_out(data,
                      AttrPrefix: false,
                      RootName: 'healthdata',
                      ContentKey: :content)
  end


  def any_service_in_state?(for_status, *service_states)
    service_states.any? do |states_set|
      states_set.any? {|s| s[:status] == for_status}
    end
  end

  def collect_service_states(service_class)
    controller_instance = service_class.new
    # pushing request into specific controller, because we need host_with_port
    controller_instance.request = request
    controller_instance.generate_address_list.collect do |address|
      query_status_all(address)
    end
  end

  def add_service_states(data, states, name)
    counter = 0
    states.each do |s|
      data["#{name}#{counter+=1}".to_sym] = [s]
    end
  end

  # IMPORTANT NOTE: this method will work only if server has at least 2 workers!
  #                 because it needs to ping its Experiment Manager status
  #                 which is server by the same Rails app
  # Queries status of serivce listening at service_address
  # Returns Hash with:
  # * status: 'failed' or 'ok' or 'warning'
  # * content (optional): an additional message
  def query_status_all(service_address, scheme='https')
    status_url = "#{scheme}://#{service_address}/status.json"
    begin
      status_request = RestClient::Request.new(
        method: :get,
        url: status_url,
        params: { tests: ['database'] },
        content_type: :json,
        accept: :json,
        timeout: 20,
        verify_ssl: OpenSSL::SSL::VERIFY_NONE,
      )
      Rails.logger.info("Will make status request to: #{status_url}")
      resp = status_request.execute
    rescue RestClient::Exception => e
      return {
        status: 'failed',
        content: "Status check request failed for #{service_address} (GET #{status_url}): #{e}, body: #{e.response}"
      }
    rescue => e
      return {
        status: 'failed',
        content: "Exception on checking status for #{service_address} (GET #{status_url}): #{e}"
      }
    end

    begin
      json_resp = JSON.parse(resp)
    rescue Exception => e
      Rails.logger.error("query_status_all: #{e}")
      return {
          status: 'failed',
          content: "Cannot parse response of GET #{status_url} " \
            "(code: #{resp.respond_to?(:code) ? resp.code : 'none'}), error: " \
            "#{e}"
      }
    end

    if resp.code == 200
      result = {
          status: ((json_resp['status'] == 'ok') and 'ok' or 'warning')
      }
      result[:content] = json_resp['message'] if json_resp['message']
    else
      result = {
          status: 'failed'
      }
      result[:content] = (if json_resp['message']
                           "Code #{resp.code}, message: #{json_resp['message']}"
                         else
                           "Error withoud message (code #{resp.code}): \"#{resp}\""
                         end)
    end

    result
  end


  def json_pretty(data)
    JSON.pretty_generate(data)
        .gsub("\n", '<br/>')
        .gsub(' ', '&nbsp;')
  end


  private :query_status_all, :add_service_states, :any_service_in_state?,
          :collect_service_states, :convert_status_to_xml
end

app/helpers/infrastructures_helper.rb
require 'infrastructure_facades/infrastructure_facade_factory'
require 'json'

module InfrastructuresHelper

  # Changes hash-data from InfrastrctureController.list to data for selector with groups
  def infrastructures_list_to_select_data(infrastructures_hash)
    disabled_keys = []
    data = infrastructures_hash.map do |first|
      first[:children] = [first.clone] unless first.has_key? :children
      [
          first[:name], first[:children].map do |second|
            key = second[:infrastructure_name]
            if second[:enabled] == false
              disabled_keys << key
            end
            [second[:name], key]
          end
      ]
    end

    {data: data, disabled: disabled_keys}
  end

  def image_secrets_select_data(user_id, cloud_name)
    CloudImageSecrets.find_all_by_query(user_id: user_id, cloud_name: cloud_name.to_s).map do |i|
      ["#{i.image_identifier} #{i.label ? i.label : ''} (#{i.image_login})", i.id]
    end
  end

  def instance_types_select_data(cloud_client)
    cloud_client.instance_types.map{|k, desc| [desc, k]}
  end

  def private_machine_credentials_select_data(user_id)
    PrivateMachineCredentials.where(user_id: user_id).map{|mach| [mach.machine_desc, mach.id]}
  end

  def infrastructure_long_name(infrastructure_name)
    InfrastructureFacadeFactory.get_facade_for(infrastructure_name).long_name
  end

  def count_simulation_managers(infrastructure_name, user_id)
    InfrastructureFacadeFactory.get_facade_for(infrastructure_name).count_sm_records(user_id)
  end

  def experiments_select_data(user)
    shared_prefix = "[#{I18n.t('infrastructure.information.shared_experiment')}] "
    user.get_running_experiments.map do |exp|
      ["#{user.owns?(exp) ? '' : shared_prefix}#{exp.name} (#{exp.id})", exp.id]
    end
  end

end

app/views/infrastructure/information/_images_manager.html.haml
-# local variables: experiment, user
- require 'infrastructure_facades/clouds/cloud_factory'

.row
  #images_manager-ajax-response.alert-box.radius(style="display: none;")

.row{class: 'panel callout radius'}
  = raw t('.info', account_link: link_to('account', user_controller_account_path))

.row
  %dl.accordion(data-accordion="")
    %dd
      %a(href='#image-submission-panel')= t('.image_submission_label')
      .content#image-submission-panel
        .row
          = form_tag add_infrastructure_credentials_infrastructure_path, remote: true, class: 'custom' do
            = hidden_field_tag 'credential_type', 'image'
            = hidden_field_tag 'experiment_id', experiment.id
            .row
              .small-4.columns
                = label_tag :infrastructure_type, t('.cloud_name') + ':', class: 'inline right'
              .small-4.columns#cloud-select
                = select_tag :infrastructure_type, options_for_select(CloudFactory.provider_names_select(user.id))
              .small-4.columns
            - CloudFactory.provider_names.map do |cloud_name|
              - secrets = CloudSecrets.find_by_query('cloud_name'=>cloud_name, 'user_id'=>user.id)
              .row{id: "image-id-row-#{cloud_name}"}
                .small-4.columns
                  = label_tag :image_id, t('.image_id') + ':', class: 'inline right'
                .small-4.columns{id: "#select-#{cloud_name}"}
                  - unless secrets.nil?
                    - begin
                      - imgs_info = CloudFactory.client_class(cloud_name).new(secrets).all_images_info
                      - select_hash = Hash[imgs_info.map{|id, info| ["#{id} (#{info})", id]}]
                      = select_tag :image_id, options_for_select(select_hash)
                    - rescue # image ids cannot be fetched - wrong credentials?
                      - secrets = nil
                  - if secrets.nil?
                    = text_field_tag :image_id, ''
                .small-4.columns

            .row
              .small-4.columns
                = label_tag :image_login, t('.login') + ':', class: 'inline right'
              .small-4.columns
                = text_field_tag :image_login, ''
              .small-4.columns
            .row
              .small-4.columns
                = label_tag :secret_image_password, t('.password') + ':', class: 'inline right'
              .small-4.columns
                = password_field_tag :secret_image_password, ''
              .small-4.columns

            .row
              .small-12.columns.text-center
                = submit_tag t('infrastructure.information.submit'), class: 'button radius'
                = image_tag 'loading.gif', class: 'image-submission-busy', style: 'display: none;'

    %dd
      %a(href='#image-table-panel')= t('.image_table_label')
      .content#image-table-panel
        %p
          %table.images{style: 'width: 100%'}
            %tr
              %th= t('.cloud_name')
              %th= t('.image_id')
              %th= t('.login')
              %th= t('.actions')
            %tbody
              - CloudImageSecrets.find_all_by_user_id(user.id).each do |image|
                - row_id = "info-row-#{image.cloud_name}-#{image.image_id}"
                %tr{id: "#{row_id}"}
                  %td
                    .small-12.columns.text-center
                      =CloudFactory.client_class(image.cloud_name).long_name
                  %td
                    .small-12.columns.text-center
                      = image.image_id
                  %td
                    .small-12.columns.text-center
                      = image.image_login
                  %td
                    .small-12.columns.text-center
                      = button_to t('.remove'), remove_image_infrastructure_path(image_secrets_id: image.id), class: "remove-button button radius tiny", remote: true, form: { "data-type" => "json" }
                  %td
                    .small-12.columns.text-center
                      = image_tag 'loading.gif', class: "#{row_id}-busy", size: '24x24', style: 'display: none;'

:javascript
  $(function() {
    new window.ImagesManagerDialog('image-submission-panel',
                                 '#cloud-select',
                                 '#extension-dialog',
                                 '.image-submission-busy');

    $('p').each(function(index, element) {
      if($(element).html() == "") {
        $(element).remove();
      }
    });
  });