config/routes.rb
require File.join(Rails.root, 'app/models/openid_providers/google_openid')
require File.join(Rails.root, 'app/models/openid_providers/github_oauth')

ScalarmExperimentManager::Application.routes.draw do

  resources :simulation_managers do
    member do
      get :code
    end
  end

  root 'user_controller#index'

  get 'login' => 'user_controller#login'
  post 'login' => 'user_controller#login'
  post 'logout' => 'user_controller#logout'
  get 'user_controller/account'
  post 'user_controller/change_password'
  get 'status' => 'user_controller#status'

  if GoogleOpenID.google_configured?
    get 'login/login_oauth_google' => 'user_controller#login_oauth_google'
    get 'login/oauth2_google_callback' => 'user_controller#oauth2_google_callback'
  end

  if GithubOauth.github_configured?
    get 'login/login_oauth_github' => 'user_controller#login_oauth_github'
    get 'login/oauth2_github_callback' => 'user_controller#oauth2_github_callback'
  end

  get 'login/login_openid_plgrid' => 'user_controller#login_openid_plgrid'
  post 'login/openid_callback_plgrid' => 'user_controller#openid_callback_plgrid'

  get 'simulation_scenarios' => 'simulations#index'
  get 'simulations' => 'simulations#index'
  get 'simulations/index'
  get 'simulations/registration'
  post 'simulations/upload_component'
  post 'simulations/destroy_component'
  post 'simulations' => 'simulations#create'

  get 'infrastructures' => 'infrastructures#index'

  resources :experiments do
    collection do
      post :start_import_based_experiment, to: 'experiments#create'
      post :calculate_experiment_size
      post :calculate_imported_experiment_size
      get :running_experiments
      get :completed_experiments
      get :historical_experiments
      get :random_experiment
    end

    member do
      get   :code_base
      get   :next_simulation
      get   :parameter_values
      get   :file_with_configurations
      get   :configurations
      get   :results_binaries

      post  :stop
      post  :extend_input_values
      get   :intermediate_results
      get   :extension_dialog
      post  :change_scheduling_policy
      post  :schedule_point
      post  :schedule_multiple_points
      get   :get_result

      post :histogram
      post :scatter_plot
      post :regression_tree
      get :scatter_plot_series

      get :running_simulations_table
      get :completed_simulations_table

      get :completed_simulations_count
      get :experiment_stats, to: 'experiments#stats'
      get :stats
      get :experiment_moes, to: 'experiments#moes'
      get :moes
      get :moes_json
      get :results_info

      get :simulation_manager

      post :share

      post :mark_as_complete

      post 'supervisor_run/state_history', action: :post_supervisor_state_history
      get 'supervisor_run/state_history', action: :get_supervisor_state_history

      get :analysis_panel
    end

    resources :simulations do
      member do
        post :mark_as_complete
        post :progress_info
        get  :progress_info_history
        get  :get_simulation_data
        get  :results_binaries
        get  :results_stdout
        post :host_info
        post :performance_stats
      end
    end
  end

  get 'simulations/simulation_scenarios' => 'simulations#simulation_scenarios'
  post 'simulations/upload_parameter_space'

  resource :infrastructure do
    member do
      post :schedule_simulation_managers
      get :infrastructure_info
      post :add_infrastructure_credentials
      get :get_infrastructure_credentials
      post :remove_credentials
    end

    collection do
      get :list
      get :simulation_managers_info
      get :simulation_managers_summary
      get :get_sm_dialog
      get :get_booster_dialog
      get :get_booster_partial
      get :get_credentials_partial
      get :get_credentials_table_partial
      get :get_resource_status
      get :simulation_manager_records
      post :simulation_manager_command
    end
  end

  resources 'simulation_scenarios' do
    member do
      get :code_base
      post :share
      get :experiments
    end
  end

  resources :clusters do
    collection do
      get :credentials
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
  Sidekiq::Web.set :sessions, Rails.application.config.session_options

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets.sidekiq_username && password == Rails.application.secrets.sidekiq_password
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :information do
    get     'status' => 'status#status'
    get     'scalarm_status' => 'status#scalarm_status'

    get     'db_instances/list'
    post    'db_instances/register'
    post    'db_instances/deregister'

    post    'db_instances' => 'db_instances#register'
    get     'db_instances' => 'db_instances#list'
    delete  'db_instances' => 'db_instances#deregister'

    get     'db_config_services/list'
    post    'db_config_services/register'
    post    'db_config_services/deregister'

    post    'db_config_services' => 'db_config_services#register'
    get     'db_config_services' => 'db_config_services#list'
    delete  'db_config_services' => 'db_config_services#deregister'

    get     'db_routers/list'
    post    'db_routers/register'
    post    'db_routers/deregister'

    post    'db_routers' => 'db_routers#register'
    get     'db_routers' => 'db_routers#list'
    delete  'db_routers' => 'db_routers#deregister'

    get 'storage/list'
    post 'storage/register'
    post 'storage/deregister'

    post 'experiments/register'
    get 'experiments/list'
    post 'experiments/deregister'

    post 'experiment_managers' => 'experiments#register'
    get 'experiment_managers' => 'experiments#list'
    delete 'experiment_managers' => 'experiments#deregister'

    post 'storage_managers' => 'storage#register'
    get 'storage_managers' => 'storage#list'
    delete 'storage_managers' => 'storage#deregister'

    post 'chart_services' => 'chart#register'
    get 'chart_services' => 'chart#list'
    delete 'chart_services' => 'chart#deregister'

    post 'data_explorers' => 'chart#register'
    get 'data_explorers' => 'chart#list'
    delete 'data_explorers' => 'chart#deregister'

    post 'experiment_supervisors' => 'supervisor#register'
    get 'experiment_supervisors' => 'supervisor#list'
    delete 'experiment_supervisors' => 'supervisor#deregister'
  end

  namespace :storage do
    get '/status' => 'log_bank#status'
    put 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#put_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#get_simulation_output'
    get 'experiments/:experiment_id/simulations/:simulation_id/size' => 'log_bank#get_simulation_output_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id' => 'log_bank#delete_simulation_output'

    get 'experiments/:experiment_id' => 'log_bank#get_experiment_output'
    get 'experiments/:experiment_id/size' => 'log_bank#get_experiment_output_size'
    delete 'experiments/:experiment_id' => 'log_bank#delete_experiment_output'

    put 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#put_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#get_simulation_stdout'
    get 'experiments/:experiment_id/simulations/:simulation_id/stdout_size' => 'log_bank#get_simulation_stdout_size'
    delete 'experiments/:experiment_id/simulations/:simulation_id/stdout' => 'log_bank#delete_simulation_stdout'
  end

end

app/controllers/api/experiments_controller.rb
require "#{Rails.root}/app/concepts/experiments/experiment_representer.rb"

class Api::ExperimentsController < Api::ApplicationController
  before_filter :load_experiment, except: [ :index ]

  def index
    render json: @current_user.experiments.sort{ |e1, e2| e2.start_at <=> e1.start_at }.map{|e|
             ExperimentRepresenter.new(e, @current_user, :short).to_h
           }
  end

  def show
    render json: ExperimentRepresenter.new(@experiment, @current_user).to_json
  end

  private

  def load_experiment
    validate(
        id: [:optional, :security_default]
    )

    @experiment = nil

    if params.include?(:id)
      experiment_id = BSON::ObjectId(params[:id].to_s)

      if not @current_user.nil?
        @experiment = @current_user.experiments.where(id: experiment_id).first

        if @experiment.nil?
          render nothing: true, status: :not_found
          return
        end

      elsif (not @sm_user.nil?)
        @experiment = @sm_user.scalarm_user.experiments.where(id: experiment_id).first

        if @experiment.nil?
          Rails.logger.error(t('security.sim_authorization_error', sm_uuid: @sm_user.sm_uuid, experiment_id: params[:id]))

          render nothing: true, status: :forbidden
          return
        end
      end
    end

    render nothing: true, status: :bad_request if @experiment.nil?
  end

end

app/controllers/information/experiments_controller.rb
class Information::ExperimentsController < Information::AbstractServiceController
  def self.service_name
    'Experiment Manager'
  end

  def self.model_class
    Information::ExperimentManager
  end

  # Override parent: add self address if no addresses are registered
  def generate_address_list
    adresses = super
    adresses.blank? ? [ request.host_with_port ] : adresses
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper

  def select_scheduling_policy
      select_tag 'scheduling_policy', options_for_select([
        ['Monte Carlo', 'monte_carlo'],
        ['Sequential forward', 'sequential_forward'],
        ['Sequential backward', 'sequential_backward']])
  end

  def json_rt_node(node, tree)
    formatted_mean = "%g" % node["mean"]
    node_question_text = node["question"] ? node["question"] : ""
    "{
      id: '#{node["id"]}',
      name: '#sim = #{node["n"]}, Mean MoE = #{formatted_mean}|#{node_question_text}',
      data: { 'param_id': '#{node["param_id"]}', 'param_label': '#{node["param_label"]}' },
      children: [#{
        if node.has_key?("left") then
          json_rt_node(tree[node["left"]], tree) + ", " + json_rt_node(tree[node["right"]], tree)
        else
          ""
        end
      }]
    }"
  end

  def share_with_users
    ScalarmUser.all.select{|u|
      u.id != current_user.id and (@experiment.shared_with.blank? or (not @experiment.shared_with.include?(u.id)))
    }.map{ |u|
      u.login.nil? ? u.email : u.login
    }
  end

  def experiment_info_button(text_prefix, reveal_id, icon, disabled)
    link_to '#', title: t("#{text_prefix}.tooltip"), 'data-reveal-id' => reveal_id, disabled: disabled,
                 class: 'button tiny radius' do

      raw content_tag(:i, '', class: icon) + raw('&nbsp;') + t("#{text_prefix}.link")
    end

  end

  def constraints_conditions
    [">", ">="]
  end

  def supervisor_options(supervisors)
    options = []
    supervisors.each do |supervisor|
      if supervisor.has_key? 'name'
        options.append [supervisor['name'], supervisor['id']]
      else
        options.append [supervisor['id'], supervisor['id']]
      end
    end
    options_for_select options, selected: options.first
  end

  ##
  # Returns workers scaling algorithm list parsed to select options.
  def workers_scaling_options
    options = WorkersScaling::AlgorithmFactory.get_algorithms_list.map { |entry| [entry[:name], entry[:id]] }
    options_for_select options, selected: options.first
  end

  ##
  # Returns workers scaling algorithms descriptions as hash [id -> description]
  def workers_scaling_algorithms_description
    WorkersScaling::AlgorithmFactory.get_algorithms_list.map {|entry| [entry[:id], entry[:description]] }.to_h
  end

  def analysis_methods
    [ 'histogram', 'scatter_plot', 'regression_tree' ]
  end

  def analysis_methods_description
    {
        "histogram" => "Histogram shows results frequency distribution",
        "scatter_plot" => "Analysis of two variables relationship with scatter plot",
        "regression_tree" => "Classification of objects by dividing the found set of conditions"
    }
  end

  def data_explorer_base_url(url)
    return url if url.blank?

    if Rails.application.secrets.information_service_development
      "http://#{url}"
    else
      "https://#{url}"
    end
  end

end

app/views/experiments/_analysis_charts.html.haml
#experiment-analysis-modal.reveal-modal(data-reveal="")
  %a.close-reveal-modal &#215;

  .histogram-analysis-content.content(style="display:none;")
    = render :partial => 'histogram_options', :object => @experiment

  .regression_tree-analysis-content.content(style="display:none;")
    = render :partial => 'regression_tree_options', :object => @experiment

  .scatter_plot-analysis-content.content(style="display:none;")
    = render :partial => 'scatter_plot_options', :object => @experiment

app/views/experiments/_basic_statistics_charts.haml
%section.panel.radius.list.analysis-chart#basic_charts_form
  %h3.subheader= t('charts.histogram.section_header')

  - notation_options = options_for_select([["Default", 'default'], ["Scientific", 'scientific']])

  .row
    .small-10.columns
      .small-3.columns
        = label_tag :moe_name, t('charts.histogram.select_moe') + ':', class: 'inline'
      .small-9.columns
        = select_tag 'moe_name', '', { class: 'moe_list' , id: "select_moe"}

  .row
    .small-10.columns
      .small-3.columns
        = label_tag :resolution, t('charts.histogram.resolution') + ':', class: 'inline', id: "label_number_of_bars"
      .small-9.columns
        = text_field_tag 'resolution', 10, id: "number_of_bars"

  .row
    .small-10.columns
      .small-3.columns
        = label_tag :x_axis_notation, "Notation on axis X" + ':', class: 'inline'
      .small-3.columns
        = select_tag 'x_axis_notation', notation_options
      .small-3.columns
        = label_tag :y_axis_notation, "Notation on axis Y" + ':', class: 'inline'
      .small-3.columns.end
        = select_tag 'y_axis_notation', notation_options
  .row
    %ul.inline-list
      %li= submit_tag t('charts.load_button'), class: 'button radius', id: "load_chart_button"
      %li= image_tag 'loading.gif', :id => 'busy_rt', size: '16x16', style: 'display: none'


#basic_charts

- content_for :javascript do
  :javascript
    var basic_chart_tab = [];

    // 'Load chart' button handler
    //$('#basic_charts_form').find('input[type=submit]').bind('click', function() { //was earlier
    $('#basic_charts_form').find('#load_chart_button').bind('click', function() {
      try {
        $('#busy_basic').show();
        var moe_name = $('#basic_charts_form select[name=\'moe_name\'] option:selected').val();
        var resolution = $('#basic_charts_form input[name=\'resolution\']').val();
        var x_axis_notation = $('#basic_charts_form select[name=\'x_axis_notation\']').val();
        var y_axis_notation = $('#basic_charts_form select[name=\'y_axis_notation\']').val();
        resolution = parseInt(resolution);

        var index_of_moe = window.moes_info.moes_names.indexOf(moe_name)
        var type_of_moe = window.moes_info.moes_types[index_of_moe]

        if (type_of_moe == "string") {
          $('#basic_charts_form').find('#number_of_bars').hide();
          $('#basic_charts_form').find('#label_number_of_bars').hide();

          $.post("#{histogram_experiment_path(@experiment.id)}",
            { 'moe_name': moe_name, 'resolution': resolution,
              'type' : type_of_moe,
              'x_axis_notation': x_axis_notation,
              'y_axis_notation': y_axis_notation },
            function(data) { $('#busy_basic').hide(); }
          );
        }
        else if(isNaN(resolution) || resolution < 1 || resolution > 100){
          toastr.error("#{t('experiments.errors.invalid_resolution')}");
          $('#busy_basic').hide();
        }
        else {
          $.post("#{histogram_experiment_path(@experiment.id)}",
            { 'moe_name': moe_name, 'resolution': resolution,
             'type' : type_of_moe,
              'x_axis_notation': x_axis_notation,
              'y_axis_notation': y_axis_notation},
            function(data) { $('#busy_basic').hide(); }
          );
        }
      } catch (e) {
        $('#busy_basic').hide();
        toastr.error("#{t('errors.loading_chart')}" + ": " + e);
      }
    });

    $('#basic_charts_form').find('#select_moe').change( function() {
      try {
        var moe_name = $('#basic_charts_form select[name=\'moe_name\'] option:selected').val();
        var index_of_moe = window.moes_info.moes_names.indexOf(moe_name)
        var type_of_moe = window.moes_info.moes_types[index_of_moe]

        if (type_of_moe == "string") {
          $('#basic_charts_form').find('#number_of_bars').hide();
          $('#basic_charts_form').find('#label_number_of_bars').hide();

        } else {
          $('#basic_charts_form').find('#number_of_bars').show();
          $('#basic_charts_form').find('#label_number_of_bars').show();
        }
        $.post("#{histogram_experiment_path(@experiment.id)}",
            { 'type' : type_of_moe },
            function(data) { $('#busy_basic').hide(); }
        );
      } catch (e) {
        $('#busy_basic').hide();
        toastr.error("#{t('errors.loading_chart')}" + ": " + e);
      }
    });

app/views/experiments/_historical_experiments.html.haml
%section.panel.radius.list
  = content_tag :h3, t('historical_experiments.label'), class: 'subheader'

  .content
    - if @historical_experiments.blank?
      %p= t('.no_experiments')
    - else
      - @historical_experiments.each do |experiment|
        - start_time, finish_time = experiment.start_at.strftime('%Y-%m-%d %H:%M'), experiment.end_at.strftime('%Y-%m-%d %H:%M')
        %a.button.expand.radius.last-element{ href: experiment_path(experiment.id) }
          - unless current_user.owns?(experiment)
            %i.fi-share
          = t('.link_text', { name: experiment.name, start_time: start_time, finish_time: finish_time })

app/views/experiments/_regression_tree_charts.html.haml
%section.panel.radius.list.analysis-chart#regression_charts_form
  %h3.subheader= t('charts.regression.section_header')

  #regression_charts_form
    .row
      .small-10.columns
        .small-3.columns
          = label_tag :moe_name, t('charts.regression.select_moe') + ':', class: 'inline'
        .small-9.columns
          = select_tag 'moe_name', '', { class: 'moe_list' }
    .row
      %ul.inline-list
        %li= submit_tag t('charts.load_button'), class: 'button radius'
        %li= image_tag 'loading.gif', :id => 'busy_rt', size: '16x16', style: 'display: none'


#regression_charts

- content_for :javascript do
  :javascript
    var rt_chart_tab = new Array();
    var rt_vis_tab = new Array();

    // 'Load chart' button handler
    $('#regression_charts_form').find('input[type=submit]').bind('click', function() {
      if (check_if_no_results_to_plot() == true){
        return;
      }

      $('#busy_rt').show();

      var moe_name = $('#regression_charts_form select[name=\'moe_name\'] option:selected').val();

      $.post("#{regression_tree_experiment_path(@experiment.id)}",
        { 'moe_name': moe_name },
        function(data) { $('#busy_rt').hide(); }
      );

      function check_if_no_results_to_plot() {
        if (window.moes_info.moes_types.length <= 0 || typeof window.moes_info.moes_types == 'undefined') {
          toastr.error("No results to plot on chart");
          return true;
        }
      }
    });

app/views/experiments/_scheduling_policy_dialog.html.haml
#scheduling_policy_dialog.reveal-modal(data-reveal="")
  %h2 Scheduling policy of the experiment

  %p
    = form_tag(change_scheduling_policy_experiment_path, :onSubmit => "$('#scheduling-busy').show()", remote: true, class: 'custom') do
      = tag(:input, type: "hidden", name: request_forgery_protection_token.to_s, value: form_authenticity_token)
      = hidden_field_tag :experiment_id, @experiment.id
      %div
        Current scheduling policy of the experiment:
        %b#policy_name=  "#{@experiment.scheduling_policy}."
      %div Select new scheduling policy: #{select_scheduling_policy}

      %div
        = submit_tag 'Submit', class: 'button'
        = image_tag 'loading.gif', :id => 'scheduling-busy', :style => 'display: none;'
        #scheduling-ajax-response

  %a.close-reveal-modal &#215;

app/views/experiments/_workers_info.html.haml
.content
  .row#workers_info
    .small-12.large-6.columns
      %ul#state.small-12.columns(style="font-weight: bold;")

      .row#workers_alert(style="display: none; margin-bottom: 10px;")
        .small-12.columns.w-failed(style="font-weight: bold")
          - if @experiment.workers_scaling
            = t('experiments.computational_resources.no_workers_alert_with_workers_scaling')
          - else
            = t('experiments.computational_resources.no_workers_alert')
      .row
        .small-8.columns
          %a{href: "#{infrastructures_path(experiment_id: @experiment.id)}"}
            = t('experiments.computational_resources.show_details_link')

    .small-12.large-6.columns
      .row
        - if @experiment.is_running
          .small-12.large-10.large-centered.columns
            %span#boostButton{class: button_classes}
              %i.fi-plus
              = t('experiments.computational_resources.boost_button')

            %a{class: button_classes, href: simulation_manager_experiment_path}
              %i.fi-download
              = t('experiments.computational_resources.get_sm_button')


- content_for :javascript do
  :javascript
    $(function() {
      monitor = new window.ExperimentResourcesMonitor("#{simulation_managers_path(experiment_id: @experiment.id)}");
      monitor.getResourcesSummary();

      setInterval(function() { monitor.getResourcesSummary() }, 30000);
    });

app/views/experiments/show.html.haml
-#- require "erb"
-# include ERB::Util

- content_for :title, 'Scalarm - monitoring'
- content_for :help, raw(t('help.experiments.monitoring'))

= render 'experiment_links'
= render 'analysis_charts'

= content_for :panel do
  .nano(style="overflow: hidden;")
    %section.row.panel.radius.nano-content(style="padding-left: 15px; padding-right: 8px;")
      %h3.text-center.subheader
        = t('experiments.menu_panel.experiment')
      %ul{id: "menu-panel", style:"list-style-type: circle;"}
        %dl.accordion{"data-accordion" => "accordion_management", style: "text-align: left;" }
          - id = "accordion#{t('experiments.menu_panel.experiment_management.header').downcase}"
          %dd.accordion-navigation.active{id: "#{id}"}
            %a.group_title{:href => "#experiments-panel", style: "text-align: left;"}
              %i.fa.fa-minus-circle.experiment{style: "color: 333"}
              = t('experiments.menu_panel.experiment_management.header')
            %ul.content.active{"id" => "experiments-panel", "style" => "background: none;"  "text-align: left;  list-style-type: circle;"}
              %li
                %a.extend_input_space_link(href="#" id="extendinputspace" data-action-url="#" style="display: block; padding: 0px;")
                  %span= t('experiments.menu_panel.experiment_management.extend_input_space')
              %li
                %a.set_scheduling_method_link(href="#" id="setschedulingmethod" data-action-url="#" style="display: block; padding: 0px;")
                  %span= t('experiments.menu_panel.experiment_management.set_scheduling_method')
              %li
                %a.set_scheduling_method_link(href= "#{infrastructures_path}?experiment_id=#{@experiment.id}" id="setschedulingmethod" data-action-url="#" style="display: block; padding: 0px;")
                  %span= "Computational resources"

        %dl.accordion{"data-accordion" => "accordion_results", style: "text-align: left;"}
          - id = "accordion#{t('experiments.menu_panel.experiment_result.header').downcase.gsub!(/\s+/, '')}"
          %dd.accordion-navigation.active{id: "#{id}"}
            %a.group_title{:href => "#experiments-result-panel", style: "text-align: left;"}
              %i.fa.fa-minus-circle.experiment{style: "color: 333"}
              = t('experiments.menu_panel.experiment_result.header')
            %ul.content.active{"id" => "experiments-result-panel", "style" => "background: none;"  "text-align: left;  list-style-type: circle;"}
              %li
                %a.download_result_link(href="#{results_binaries_experiment_path(@experiment.id)}" id = "downloadbinaries" data-action-url="#" style="display: block; padding: 0px;")
                  %span= t('experiments.menu_panel.experiment_result.download_result.binaries')
              %li
                %a.download_result_link(href="#{file_with_configurations_experiment_path(@experiment.id)}" id = "downloadcsv" data-action-url="#" style="display: block; padding: 0px;")
                  %span= t('experiments.menu_panel.experiment_result.download_result.configurations')

      %hr
      %h3.text-center.subheader
        = t('experiments.menu_panel.analysis.header')

      %ul.analyses-panel{style: "text-align: left; list-style: none;"}

%section
  %section.row.panel.radius
    = render 'information_panel'

  - if @experiment.is_running
    %section.panel.radius
      %h3.subheader
        = t('experiments.computational_resources.title')
        = image_tag('loading.gif', id: 'actions-loading-workers')
      = render 'workers_info'
      - if @experiment.workers_scaling
        = render 'workers_scaling'


  %section.row.panel.radius.last-element#monitoring_section
    %h3.subheader= t('experiments.show.stats_header')

    .content(style="padding-top: 30px; position: relative;" )


      = render 'monitoring_stats'
      .speedometer.show-for-large-up{id: "speedometer_#{@experiment.id}"}

      %article#experiment_progress_bar(style="padding-top: 50px; margin-bottom: 40px" )
        %h4#header_progress_bar.hidden.subheader= t('.progress_bar_header')

      = render 'monitoring_actions'

  %section.row.panel.radius.last-element#progressInformationWrapper(style="margin-top: 50px;")
    = render 'monitoring_table'

  = render 'scheduling_policy_dialog'

- unless @experiment.supervised.nil?
  %section.panel.radius(style="margin-top: 20px;")
    = render 'experiment_result'

- content_for :javascript do
  :javascript
    $(function() {
      var booster = new window.ExperimentBooster('booster_dialog');

      var experiment_id = "#{@experiment.id}";
      $("#panel .analyses-panel").load("#{analysis_panel_experiment_path(@experiment.id)}");

      $("ul.analyses-panel li a").mouseenter(function() {
        $(this).css("background-color", "#EEE");
      });
      $("ul.analyses-panel li a").mouseleave(function() {
        $(this).css("background-color", "#f5f5f5");
      });

      new window.ExperimentSpeedometer(experiment_id).show();

      var monitor = new window.ExperimentMonitor(experiment_id);
      monitor.generate_html('experiment_stats');
      
      window.toggle_panels_on_title_click();

      $(document).foundation();

      // websockets disabled due to lack of WS support in scalarm_data_explorer
      /*
      window.WebSocket = window.WebSocket || window.MozWebSocket;

      if (chart_service_url) {
        try {
          var ws = new WebSocket("wss://" + chart_service_url + "/experiment_progress/" + experiment_id);
          window.onbeforeunload = function() {
            //Connection closed on Download simulation manager!!
            ws.onclose = function () {}; // disable onclose handler first
            ws.close()
          };

          ws.onmessage = function(message) {
            console.log("refreshing progress bar...");
            console.log(message.data);
            monitor.update_bar(message.data);
          };

          ws.onerror = function(message) {
            console.log(message);
          }
        }
        catch (e) {
          console.log(e);
          console.log("Unable to establish WebSocket connection.");
        }
      }
      */

    $("#setschedulingmethod").bind("click", function() {
        $('#scheduling_policy_dialog').foundation('reveal', 'open');
        $('#scheduling-ajax-response').html('');
      });

      $("#showprogress").bind("click", function() {
        $('#progressInformationWrapper').slideToggle();
        $('html, body').animate({ scrollTop: $('#progressInformationWrapper').offset().top }, 1000);
      });

      $("#extendinputspace").bind("click", function() {
        $('#actions-loading').show();
        $('#extension-dialog').load("#{extension_dialog_experiment_path(@experiment.id)}", function() {
          $('#actions-loading').hide();
          $('#extension-dialog').foundation('reveal', 'open');
        })
      });

      $("#downloadresult").bind("click", function() {
        if ($('#download-options').is(":visible"))
          $('#download-options').hide();
        else $('#download-options').show();
      });

      $("#menu-panel").on("click", "a.group_title", function (){
        var accordion_id = "#accordion" + $(this).text().toLowerCase().replace(/\s/g, '');
        if(!$(accordion_id).hasClass("active")) {
          $(accordion_id).find('i').addClass('fa fa-minus-circle experiment');
        }
        else {
          $(accordion_id).find('i').removeClass('fa fa-minus-circle experiment').addClass('fa fa-plus-circle experiment');
        }

      });

    });